### ISSUE TITLE
Create “docs” folder for core team processes/todo templates.

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#168]
Docs Templates:

- [x] Hack Night/Event Todos (see #166 )
- [x] Onboarding new coreteam (see #160 )
- [x] ~~Move Slackin docs to open-austin-org repo.~~ 
- [ ] AWS instance setup
- [ ] ~~Streamline partnering with non-profits like Texas Appleseed~~

**Comment by mateoclarke** [comment]
Maybe this should've been a ticket on https://github.com/open-austin/open-austin.github.io

That's where we decided this folder would live.

**Comment by mateoclarke** [comment]
https://github.com/open-austin/iced-coffee/blob/master/hack-event-checklist.md

**Comment by luqmaan** [comment]
We've ended up putting the stuff in the open-austin/iced-coffee repo. We can move it later.
