### ISSUE TITLE
June 20 Open Gov & Civic Tech Meetup Checklist

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#171]
- [x] Confirm venue
- [x] Confirm speakers
    - [x] ~~Becca~~
    - [x] Diego
    - [x] Paul
    - [x] Amalie
    - [x] Nik
    - [x] Victoria
- [x] Email announcement
- [x] [Slides](https://docs.google.com/presentation/d/1aJPnMyh-PBQ0HTfA1dNPRzrZT2949-P5ww5U_2Tab6U/edit?usp=sharing)
- [x] Twitters/Facebooks, etc
- [x] Bring swag, projector, banner
