### ISSUE TITLE
Women Who Open Data Event: Oct 1st

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#174]
**What?**: Workshop style event with 4-6 presentations related to open data, code, and civic tech. Simultaneous Civic Hack Saturday for folks to hack on projects.
**When?**: October 1st, 2016
**Where?**: Dev Bootcamp, 1705 Guadalupe St.

### Workshops

- Holly Gibson (Women Who Code) - Databases: SQL vs NoSQL **(confirmed)**
- Whitney O'Banner (Dev Bootcamp) - Git **(confirmed)**
- Hailey Pate (City of Austin) and/or Julia Robbins (City of Austin) - Intro to Open Data resources, APIs, data munging tools, etc **(confirmed)**
- Resources and how-tos for web mapping with open data (maybe Sara Safavi or Andy Wilson from Maptime ATX) **(Mateo reached out)**
- Amalie (Open Austin) - PANDA Community Data Portal
- Data journalism (maybe Becca A from Texas Tribune) **(interested)**
- showcase of projects that use open data?

### Agenda
- 9am: Setup & Breakfast
- 10:00am: Workshop 1 - Hailey Pate, City of Austin, Open Data Initiatives, websites, resources, 
- 10:30am: Workshop 2 - Julia Robbins, City of Austin,  Open Data Use Case: Construction Permits 
- 11:00am: Workshop 3 - Sara Safavi, Maptime ATX
- 11:30am: Workshop 4 - Becca A from the Texas Tribune
- 12:00pm: Workshop 5 - Whitney O'Banner, Dev Bootcamp, Intro to Git
- 12:30pm: Workshop 6 - Holly Gibson, Women Who Code, Databases: SQL vs NoSQL
- 1:00 pm: Free Hack Time
- 2:00pm: Cleanup & High-fives

### Todos

- [x] RSVP: Eventbrite or Meetup or both?
- Dev Bootcamp will contribute $150-$200 for food. Do we need more sponsors?
- [x] Flesh out flyer?
- [x] Finalize speaker list
- [x] Time details

![wmopendata](https://cloud.githubusercontent.com/assets/5697474/16714901/793f93a8-4696-11e6-8c5f-61af506efe2c.jpg)

**Comment by amaliebarras** [comment]
Dope! I emailed Becca this morning :)

**Comment by amaliebarras** [comment]
Becca responded today

"Thanks for reaching out again. I'd love to be part of the event, but I'm not sure that I'll be available for the whole day. Do you have a particular time in mind or is it flexible?"

**Comment by amaliebarras** [comment]
Becca would like the 11:30 slot! Updating the issue.

**Comment by SaraChicaD** [comment]
Let's sign Holly up for the 130 slot please thx!
