### ISSUE TITLE
Set up & Start Mail Chimp Newsletters

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#184]
Meeting with @mapineda on Friday at 3pm to start getting stuff organized for the newsletter. 

## ToDo: 
- [x] Create Account
- [x] Establish frequency of emails (1st and 3rd tuesday of month @ 11amCST)
- [x] Create/choose Template
- [x] set up mailing list
- [x] Create Google doc for coreteam to contribute content  
- [x] import member xls @amaliebarras
  
## Ideas of things we can highlight
- Upcoming Events
- Highlight recent blog post
- Highlight a project that needs help or is making good progress
- Rose Bud Thorn (could also be weekly blog post)
- More ideas welcome. 

Any thoughts on when or how often we should put out emails? I think we can start by doing something twice a month.

**Comment by mapineda** [comment]
Newsletter Planning Doc
https://docs.google.com/document/d/1dzLzV1nvLCuqWSV0lQjenrmZtY7FahsQecwoaxGcsK0/edit

**Comment by VictoriaODell** [comment]
emails + name: 
https://docs.google.com/spreadsheets/d/1dghpcswCfUOsEnSKM6m-SM5-HHHaISDRFiAYU7RO2Kk/edit#gid=1952773302

**Comment by mapineda** [comment]
http://www.practicalecommerce.com/articles/83137-28-Free-Responsive-Email-Templates

**Comment by mateoclarke** [comment]
I would like to schedule the August newsletter to go out as soon as possible. There are two CityUp events this week plus Civic Hack Saturday. 

What is left? How do I help?

**Comment by amaliebarras** [comment]
Let’s also include this in the newsletter, from Becca A. :

I wanted to let you know that we're hosting a civic social weekend called "Texas Turnout" w/ SND Makes and the Knight Foundation Aug. 26-28. Applications are open now. We'd love for [Open Austin folks] to apply. Here's more info: https://www.texastribune.org/texas-turnout/ <https://www.texastribune.org/texas-turnout/>

**Comment by VictoriaODell** [comment]
Hey ya'll, 

I have a bit of a backlog. I need to pick the template + organize the content. 
@mapineda can you give me access to the google doc you posted? I can't access it with my email. 
Also, did we get the list imported?

**Comment by VictoriaODell** [comment]
Made the first newsletter template thing
It's under the campaign called "Bi-weekly Newsletter" 

I need to shrink the images but let me know what ya'll think + check links and stuff. 
We have down that we would send the 2nd & 4th Tuesday but that's up for discussion I think~

https://us13.admin.mailchimp.com/campaigns/

**Comment by VictoriaODell** [comment]
I added our logo and adjusted the pictures some. Can you check it out @mapineda ?

**Comment by mateoclarke** [comment]
This looks great!

Can we add an announcement that we (@mscarey) is working on the Candidate Questionnaire for City Council candidates?
https://docs.google.com/document/d/1_vRsdtyyb3d5gcHZn8OoS3b61OCbfGnpYJmY6Dl6V6s/edit?usp=sharing

**Comment by mapineda** [comment]
@VictoriaODell All contacts have been imported. This includes the googleGroups csv from @amaliebarras. I had to go through and parse first names from full names. Total subscribers: 421

**Comment by mapineda** [comment]
@amaliebarras & @mateoclarke I've added both Information about the Candidate Questionnaire and the Texas Turnout event 

Feel free to submit Content to future newsletters through The Newsletter Content Planning Sheet https://docs.google.com/document/d/1E1QGjLEWObfBsTN6IXt1eNu6Dggmm_4W6emLbhllAFQ/edit?usp=sharing

**Comment by mapineda** [comment]
@VictoriaODell Newsletter looks great! I added an Announcements section to the top and added the Texas Turnout to the Event section. Let me know what you think. Let's send it out today and then make it a goal of 2nd and 4th Tuesday (up for discussion) - I've marked send outs on the calendar for August.

**Comment by VictoriaODell** [comment]
Sweet~
I changed the language a bit on the policy bit. 
Want to send a test email to core-team first @mapineda?

**Comment by mapineda** [comment]
Yes!

Marco Pineda

**Comment by VictoriaODell** [comment]
Sent a test email. Should be in everyone's inbox on core team. 

Probably need a better header. Please review and we can send in the am. Sorry missed the today mark @mapineda I'm barely getting to my computer since leaving work. :x

**Comment by mapineda** [comment]
Got the test email, reviewed, looks good!

**Comment by VictoriaODell** [comment]
Posting the link for newsletter contribution in our Iced-coffee read me for future reference. 
Other newsletter related stuff will go in Open Austin> Admin/Core Team Docs> Newsletter
