### ISSUE TITLE
April 8 Leadership Meeting

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#245]
1. Values
2. Entity Formation
    - accounting
3. Membership UX
4. Projects

- Working Open Workshop, May 8th
    - registration form [need link]()
    - Mozilla Global Sprint, remote hackathon, May 1-2 [need more details]()
- Upcoming events:
  - ATX Hack 4 Change
      - Need help promoting the event and workshops [add link]()
      - Need help getting volunteer registration & project submission [add links]()
      - National Day of Civic Hacking is going to be in Sept 23rd coordinated by CfA
  - Need space CHS for May & June

### Todos
- [x] Update links
- [x] Make comments on Values doc
- [x] Add ppl to CfA Slack

**Comment by mateoclarke** [comment]
## Entity Formation
- Mission Statement (broad)
  - Parks Foundation/ Library Model
- Leadership (transient vs Exec Dir)
- Calendar
- Board of Directors (working internal leadership) vs Board of Advisors (external partners)
- Bylaws
- Formalize Membership Roster, informal membership check
- assets (like open-austin.org)

**Comment by mateoclarke** [comment]
## Values

#215 
https://docs.google.com/document/d/1OujyBccPpepUXSY5_nP3alzvd81WlCKSeSf_-sU5K-U/edit

**Comment by mateoclarke** [comment]
## Membership UX

- messaging at meetings
- referring people to Get Involved page
- purpose of event
   - contributor, leads
- [ ] is there anyone outside this group that has working on a successful project
