### ISSUE TITLE
Issue Template 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#328]
**Owner:** Person who completes the task. Also the "Assignee"
Vickie 

**Supporter:** People available to help with the tas  
Leadership Team 

**Task description:** 
Make a template to be used for our team to-dos

**Outcome:** 
Help us organize and understand the task we are sharing. 

**Next Steps:** 
- [ ] 10/15 estimated date and list item 
- [ ] 11/20 estimated date and list item 
- [ ] 12/01 estimated date and list item

**Comment by VictoriaODell** [comment]
Issue template is live here: 
https://github.com/open-austin/iced-coffee/blob/master/ISSUE_TEMPLATE.md

We can edit as needed.
