### ISSUE TITLE
Onboard James to Leadership. 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#329]
**Owner:** Person who completes the task. Also the "Assignee"
Vickie 

**Supporter:** People available to help with the task  
Leadership Team 

**Task description:** 
Get James all set up to contribute to the Open Austin team. 

**Outcome:** 
@JMensch has access all the resources and can be an active part of our team!

**Next Steps:** 
## Onboarding Steps

- [x] invite to #icedcoffee Slack channel
- [x] Update leadership page on website
- [x] add to [github org admin group](https://github.com/orgs/open-austin/teams/leadership/members)
- [x] add to [@leadership slack user group](https://open-austin.slack.com/admin#user_groups)
- [x] access to open austin google drive
- [x] access to google calendar
- [x] access to lastpass
- [x] link to core team roles
- [x] set up with [email](https://github.com/open-austin/server-configs/blob/master/email/virtual)

**Comment by VictoriaODell** [comment]
Core team doc we have: 
https://docs.google.com/document/d/1kbS0wJj9o_Xr5yKBJ2oF9_wAPscZ2gksnOyMMuqVHk4/edit?usp=sharing

A little outdated. Need to dig up the lastpass password and set up with email!

**Comment by VictoriaODell** [comment]
Was added to the email earlier and has the lastpass password.
