### ISSUE TITLE
2019-01-29 Leadership Meeting Action Items

### ISSUE THREAD

**Issue by JMensch** [open-austin/iced-coffee#335]
**Owner:** Person who completes the task. Also the "Assignee"
Leadership Team 

**Supporter:** People available to help with the tas  
Leadership Team 

**Task description:** 
Action items from the leadership meeting on 2019-01-29. Notes [here](https://docs.google.com/document/d/1g0DgVp9wEIr_511qtxrqFZmDY02DHXB6p_T8kRZt9b4/edit?usp=sharing).

**Outcome:** 
Complete the tasks before the next leadership team meeting (the week of 2/11).

**Next Steps:** 
- [x] @JMensch take [hypotheses statements](https://docs.google.com/document/d/1496blTOmAblN-dRtmEZoaQn7xPn8ZCrJxXucNjj5WL8/edit?usp=sharing) and create questionnaire first draft by 1/31
- [x] @JMensch audit iced-coffee issue list and remove stale issues.
- [ ] @JMensch create leadership meeting issue template
- [x] @mateoclarke coordinate leadership meeting week of 2/11
- [x] @stepwinder update 2/4 presentation for community discussion
- [x] @JMensch add next steps to github
- [x] @JMensch to meet with Oli on 1/31 re: leadership, interest in project onboarding
- [ ] @VictoriaODell write first draft of 2019 vision options
- [x] @VictoriaODell write slides for 2/4
- [ ] @open-austin/leadership noodle on major/minor leadership team positions
- [x] @JMensch review plan for community discussion on 501c3 [here](https://docs.google.com/document/d/1l6AoBgoxnCVdEpjSeLXJMLX1jOxOsCKproqUSt8qtRQ/edit?usp=sharing) and add basic thoughts, concerns, etc.
- [ ] @mateoclarke review plan for community discussion on 501c3 [here](https://docs.google.com/document/d/1l6AoBgoxnCVdEpjSeLXJMLX1jOxOsCKproqUSt8qtRQ/edit?usp=sharing) and add basic thoughts, concerns, etc.
- [x] @mscarey review plan for community discussion on 501c3 [here](https://docs.google.com/document/d/1l6AoBgoxnCVdEpjSeLXJMLX1jOxOsCKproqUSt8qtRQ/edit?usp=sharing) and add basic thoughts, concerns, etc.
- [x] @VictoriaODell review plan for community discussion on 501c3 [here](https://docs.google.com/document/d/1l6AoBgoxnCVdEpjSeLXJMLX1jOxOsCKproqUSt8qtRQ/edit?usp=sharing) and add basic thoughts, concerns, etc.
- [x] @stepwinder review plan for community discussion on 501c3 [here](https://docs.google.com/document/d/1l6AoBgoxnCVdEpjSeLXJMLX1jOxOsCKproqUSt8qtRQ/edit?usp=sharing) and add basic thoughts, concerns, etc.

@open-austin/leadership if any tasks require further discussion please create an issue and link it here.

**Comment by JMensch** [comment]
Adding the [Member survey rough draft](https://docs.google.com/document/d/1ug0NVFWGVcqo74Clpo8gpGP2YI8ICh5EDZJ3I5j9nTc/edit?usp=sharing) here for recordkeeping.
