### ISSUE TITLE
2019-02-13 Leadership Meeting Action Items

### ISSUE THREAD

**Issue by JMensch** [open-austin/iced-coffee#337]
**Owner:** Person who completes the task. Also the "Assignee"
Leadership Team

**Supporter:** People available to help with the tas
Leadership Team

**Task description:**
Action items from the leadership meeting on 2019-02-13. Notes [here](https://docs.google.com/document/d/1bMldlr-4_WgcQYVu-_Z4vEivoQLrWs3aQQFHxAxGUko/edit?usp=sharing).

**Next Steps:**
- [x] @VictoriaODell to send @JMensch  brief template
- [ ] @JMensch to fill out brief & informally formalize project team for project intake
- [ ] Team to noodle on process for increasing visibility into leadership sync - Quarterly and open. 
- [x] Team to video call once a month (wednesday) at 6.
- [x] Team to add “what we’re doing this week” and “if you’re blocked” every Monday
- [ ] Next steps for community conversation 
- [x] @VictoriaODell  Doodle follow up for in person meeting for Leadership Team. 
- [ ] @mateoclarke  Need to surface Bylaws in an easy to find place, iced-coffee readme? website?
- [x] @JMensch to give @VictoriaODell blurb for NAC
- [ ] @JMensch to write blog post for NAC
- [ ] @VictoriaODell to follow up with Allyson for NAC
- [ ] Everyone to look at OA Community Survey
- [ ] Everyone to review VO’s 2019 programming doc
- [ ] @VictoriaODell  to articulate programming vision / philosophy in programming doc

**Comment by JMensch** [comment]
@open-austin/leadership I don't remember if we're doing biweekly or monthly video calls and I didn't note it. Can anyone refresh my memory?

**Comment by VictoriaODell** [comment]
@JMensch weekly check in on Monday's and Biweekly video calls! First one should be next week on Thursday from 6-6:50 pm, at least I'm pretty sure that is what I believe we agreed on.

**Comment by VictoriaODell** [comment]
@JMensch we said it would be ideal to have one quarterly meeting at a place like Lazarus that is more open.

**Comment by mscarey** [comment]
I put the bylaws on [open-austin.org/about/](https://www.open-austin.org/about/), if that counts as "* easy to find"

**Comment by mateoclarke** [comment]
I'm going to close this out since I think we've knocked out all these tasks or they may be less relevant. If I'm wrong, we can reopen or create individual issues...
