### ISSUE TITLE
Schedule CfA checkin with Open Austin

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#339]
**Task description:** 
Veronica Young (CfA) is going to transfer funds in the form of a grant to OA. They want to have more frequent check-ins with brigades. We also have questions about the CfA Community Fellowship based on how Rohan's project went this year.

Vickie will coordinate with James (or an alternative second leadership member to join the call)

**Owner:** Person who completes the task. Also the "Assignee"
@VictoriaODell  

**Supporter:** People available to help with the task
@JMensch  (We nominated him without his presence so he can veto. Seemed like a good idea given James' interest in CfA happenings, NAC, etc) 

**Next Steps:** 
- [x] set a time to speak in the next couple weeks
- [x] ask questions about CfA Fellowship
- [ ] get details about funds transfer
- [x] report back to leadership team

**Comment by mateoclarke** [comment]
This got moved over the the "Done" column on our board. Is it ok to close out? Going to close, but please add comments and reopen if that was wrong.

My understanding is the conversation with Veronica at CfA has happened and they told us it would take a couple weeks before the fund transfer could be initialized.
