### ISSUE TITLE
Next Community Action Night (March/April)

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#342]
**Task description:** 
- We decided in our [last leadership sync](https://docs.google.com/document/d/1fCOaGGfbkXfmbKJ7UpmBQ9GJcAhfwiemJSE3pMjPtC4/edit#) not to try to rush to schedule a CAN next for week but that we should have a project-focused night ASAP. 
- We proposed moving the currently scheduled April 1st Terrazas meeting to Faulk and making it project focused. As we don't have any speakers/programming scheduled for April, this would save us event planning effort. Focusing specifically on the ~5 breakouts below
- This plan would be dependent on 1) consensus with leadership team 2) Faulk availability confirmation with Innovation Office. We could also look into using Central Library in some capacity if Faulk is unavailable. 

Proposed Breakouts:
- ScraPD - Remi
- Influence TX, Amy
- Policy team
- Affordable Housing - Rohan
- Dockless Data (if there is community interest)

**Owner:** Person who completes the task. Also the "Assignee"
Vickie 

**Supporter:** People available to help with the tas  
Leadership Team 

**Next Steps:** 
- [x] Confirm plan with Leadership team that wasn't at the 3/13 sync 
- [x] Vickie to confirm space availability at Faulk with Sabine at Innovation Office (IO)
- [x] Start the convo with IO about space reservations for the rest of 2019

**Comment by VictoriaODell** [comment]
Sent an email to Sabine. Also, @mateoclarke has found an alternative space if needed.

**Comment by VictoriaODell** [comment]
Space secured. 

We need to reach out to project champions and I'll update the event page and make an announcement in slack. Having 1-2 projects to share would be nice.

**Comment by mateoclarke** [comment]
I think we can close this out. Just need to confirm with @mscarey what project pitches are happening.
