### ISSUE TITLE
Complete 2020 MOU w/ CfA

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#372]
**Owner:** Person who completes the task. Also the "Assignee"
James & Mateo

**Supporter:** 
Leadership Team 

**Task description:** 
https://docs.google.com/document/d/1w-aakwLPvwuNhvVzC_HPp6PtuG_a8GwIZm6ML_M_fQk/edit#heading=h.reujit92iqh1

**Outcome:** 
Get in proper status with CfA for 2020. This make us eligible for funding for Brigade Summit & Brigade Congress 

**Next Steps:** 
- [ ] weekend of 12/14 review FAQ
- [ ] week of Mon 12/16 share thoughts and concerns with leadership team
- [ ] ASAP review and submit MOU
