### ISSUE TITLE
Issue 1099 forms for 2021

### ISSUE THREAD

**Issue by mscarey** [open-austin/iced-coffee#376]
**Owner:** Person who completes the task. Also the "Assignee"
Matt

**Task description:** 
Issue the 1099 forms for the two payments requiring them in 2021

**Outcome:** 
The IRS allows us to fill out these tax forms and issue them to the payees.

**Next Steps:** 
- [ ] fill out and send the form
  - [ ] get access to a web 1099 form that is legal to fill out (while a copy of the 1099 form exists on the IRS website, it says that the 1099 form is [illegal to fill out](https://www.irs.gov/pub/irs-pdf/f1099nec.pdf).
    - [ ] get an IRS "[Filing Information Returns Electronically (FIRE)](https://www.irs.gov/e-file-providers/who-can-participate-in-fire)" account
      - [ ]  get an IRS [TCC account](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire#How%20to%20Connect%20to%20the%20FIRE%20System%20with%20TLS) (required to apply for a FIRE account)
        - [ ] send the IRS an "[IR Application for TCC](https://la2.www4.irs.gov/esrv/esam/pages/landingPage.xhtml)." There are many TCC application forms with obscure names, but this appears to be the only one that we qualify for. 
          - [ ] Troubleshoot crashing IRS website. Currently when I submit the filled-out "IR Application for TCC" form, the IRS website crashes with the message "Access Denied
You don't have permission to access "http://la2.www4.irs.gov/esrv/esam/pages/appCommonEditFirm.xhtml" on this server.
Reference 18.7fb72d17.1643517480.205115c"
           - [x] create IRS personal identity account (for Matt). This is required for filling out a TCC application. The IRS's web service for creating new personal accounts was down for most of the time from October through early January, but I have been able to create this account now.

  - [ ]  OR: receive paper 1099 forms in the mail
    - [x]  [request](https://www.irs.gov/businesses/online-ordering-for-information-returns-and-employer-returns) that the IRS mail paper forms to us. I've sent the request twice. The IRS is currently [way behind in responding to its mail](https://www.washingtonpost.com/business/2022/01/14/irs-processing-delays/), with a backlog of 5 million items.

**Comment by mscarey** [comment]
I used a third-party service to send the forms. Closing this.
