### ISSUE TITLE
Plan for Code Across

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#45]
### Notes from #41
- YES! another ideathon
- nah to a Waffle.io style Hackshop event? http://blog.waffle.io/nc-open-data-hackshop/
- want to hear ideas from other groups, like AURA, City Departments, non-profits, etc.

### Todo
 - [x] Reach out to Diana, Lope about UX stuff
 - [ ] figure out sponsorship
 - [ ] figure out venue

**Comment by VictoriaODell** [comment]
Code Across is March 5th correct? So we have about a month and a half to plan. 

Here are some quick links to previous Code Across Documents we should refrence and update for planning:
- [Code Across 2015 Planning ](https://docs.google.com/document/d/1kQnNlsQzMHfzP4qIWhEFyTR85EuPDUVGtw_cTdlF-B0/edit#heading=h.6drmge15o9ys)
- [Code Across 2015 Agenda](https://docs.google.com/document/d/1q2wPe0Msd0qoF5XRR7AOzU-lh5JlzYUc0xWR-uIx1pM/edit)
- [Sponsor Prospectus 2015](https://docs.google.com/document/d/14CKWBctEVvjCnge1BYnUDoDOSNHWI62yGMxsDS6x_2A/edit)

The Google Drive to the 2015 Code Across folder is [Here](https://drive.google.com/drive/u/0/folders/0B1cMlEZm_nJ0RG1Sd283LXpTY1U)

Probably should go over and update the planning document first.

**Comment by VictoriaODell** [comment]
I saw you created a list of potential sponsors for 2016. We should try to get names associated with these places if we can. Or at least best email to reach someone.  
[Potential 2016 Sponsors](https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit)

Thoughts?

**Comment by mateoclarke** [comment]
yup, great idea.I have a contact for at least half of these places.

**Comment by mateoclarke** [comment]
Going to close out this issues since we are breaking Code Across todo into smaller issues with the Code Across America Milestone
