### ISSUE TITLE
Space Planning

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#65]
Start a running list of places we could go to host our events as we grow or need to accommodate larger crowds.

**Comment by mateoclarke** [comment]
Patti said Galvanize is a new bootcamp that is opening up a big new space on 2nd street in March:
> Host an event in our beautiful space, launching in March
> Visit our [Austin website here](http://www.galvanize.com/campuses/austin-2nd-street-district/#.Vpqc1ZMrJE4) or you can email me at lee.ngo@galvanize.com.

 Also added them to the [potential sponsors list](https://docs.google.com/document/d/1pAsvnfr_6t6vkTax5NPfv6os8ZNLf_p4DzAVCT4YQrE/edit).

**Comment by mapineda** [comment]
I'll reach out and contact them.

**Comment by mapineda** [comment]
Open-Source co-working is another potential venue. Attended the last Refresh Austin event they had there. Decent main space and smaller break-away offices. http://www.opensourcecoworking.com/

**Comment by mateoclarke** [comment]
This issue had a long list of options. We should turn these options into a Spreadsheet.
https://github.com/open-austin/iced-coffee/issues/88

**Comment by VictoriaODell** [comment]
Plz add things here PLZZ

https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=516533352

**Comment by VictoriaODell** [comment]
Adding the resources from issue #107 that we need to put into the doc^^ 
https://library.austintexas.gov/sites/default/files/u20/meeting_spaces_2015.pdf
![image](https://cloud.githubusercontent.com/assets/10767430/13899929/e3bb2134-edc7-11e5-8dc4-97e5e9ffc713.png)

**Comment by mateoclarke** [comment]
So at our 6/1 coreteam huddle we talked about getting a consistent space for Civic Hack Nights and Civic Hack Saturdays at least through Nov/Dec when the new Central Library opens.

## TODOS:
- [ ] Follow up about Return Path @luqmaan 
- [ ] ask for $ @luqmaan 
- [ ] Research more spaces where we can get a consistent commitment, 2-3 events per month @mateoclarke @mscarey @mapineda @luqmaan 
- [ ] Figure out if Chicon Collective can be a consistent location for Saturdays, need to pay? or a formal MOU? @mapineda 

Here is a [spreadsheet with a list of places](https://docs.google.com/spreadsheets/d/1cO4vRogh3-ytbwRA2goaQtrQE3WPVdRRzaHjP-94elU/edit#gid=170603235). We should continue to add venues here. I think we should: 
1. Identify a potential venue
2. Discuss whether if would be a good fit.
3. Do a site visit if necessary.
4. Ask them for a list of dates and confirm with MOU.

**Comment by mateoclarke** [comment]
Another todo
- [ ] Figure out if and when we want to use our last event at Urban Co-Lab @luqmaan

**Comment by mateoclarke** [comment]
Think we've established a good rhythm with hosting venues for now. Going to close this now.
